### ISSUE TITLE
 Ссылки на видео интенсива

### ISSUE THREAD

**Issue by vovs03** [manchenkoff/skillbox-async-chat#1]
# 🎦 Ссылки на видео интенсива 

_Дата:_ 6-8 апреля 2020 года

## 1. Основы Python

- https://live.skillbox.ru/code_int/online/060420 
- https://youtu.be/emeFusIWDJM

## 2. Работа с сетью (TCP)

- https://live.skillbox.ru/code_int/online/070420 
- смотреть [YouTube](https://youtu.be/jXncZI4iBa4)

## 3. Интерфейс мессенджера (PyQT)

- [На сайте SkillBox](https://live.skillbox.ru/code_int/online/080420) `https://live.skillbox.ru/code_int/online/080420`
- смотреть [YouTube](https://www.youtube.com/watch?v=8hTHQuiabp8) `https://www.youtube.com/watch?v=8hTHQuiabp8`

**Comment by mkrt-oleg** [comment]
Спасибо! Было интересно послушать. -- С уважением, Олег Витальевич Мкртычев!Sincerely, Oleg Mkrtychev! Просьба ко всем моим соотечественникам-корреспондентам: пишите свою фамилию, имя и отчество, а не имя, фамилию! Такова традиция русской манеры общения. И я не вижу причин от неё отказываться во внутренней переписке в пользу американской или в пользу "общемирового тренда перевести всё в цифру", и называть друг друга по номеру, напр. "уважаемый корреспондент №16/26.36". Если Вы согласны с этим, не поленитесь, потратьте ещё пару мгновений, чтобы написать своё отчество.   09.04.2020, 00:39, "Vovs Rubychief" <notifications@github.com>: 🎦 Ссылки на видео интенсиваДата: 6-8 апреля 2020 года1. Основы Pythonhttps://live.skillbox.ru/code_int/online/060420https://youtu.be/emeFusIWDJM2. Работа с сетью (TCP)https://live.skillbox.ru/code_int/online/070420смотреть YouTube3. Интерфейс мессенджера (PyQT)На сайте SkillBox https://live.skillbox.ru/code_int/online/080420смотреть YouTube https://www.youtube.com/watch?v=8hTHQuiabp8—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
